language: java
sudo: false
notifications:
  email: false
before_install:
  - chmod +x gradlew
install:
  - ./gradlew setupCIWorkspace -S
script:
  - ./gradlew build check
os: linux
jdk: oraclejdk8
global_env: TERM=dumb
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper