language: java
sudo: false
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build check sonarqube
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  - directories:
    - ./libs
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
os: linux
jdk: oraclejdk8
global_env: TERM=dumb
group: stable