language: java
sudo: false
notifications:
  email: false
install: true
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build check
cache:
  directories:
    - ~/.gradle